services:
  - type: web
    name: st-albert-attendance-system
    env: static
    buildCommand: corepack enable && pnpm install && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /static/*
        name: Cache-Control  
        value: public, max-age=31536000, immutable
    envVars:
      - key: NODE_VERSION
        value: 20.10.0